### ISSUE TITLE
Cassandra Channel || Contained/Reference concept support for Cassandra Channel

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#101]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |        6.3.0         |
| OS Type?     |                 |
| OS Version?           |                 |

Can you please confirm if contained/reference concept can be supported for cassandra channel?

**Comment by praagraw-tibco** [comment]
Attaching logs for contained/referenced 
[CassChannel_contref_Consumer_V1.log](https://github.com/TIBCOSoftware/be-contribution/files/11458677/CassChannel_contref_Consumer_V1.log)

**Comment by praagraw-tibco** [comment]
I have provided two projects below: "CassandraStore_ContainedReference" is used for insertion of data using store catalog function and CassandraAsChannel is used as consumer at BE. Below are the queries I have used for creating tables in DB.

DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student(studId BIGINT, fees DOUBLE, name TEXT, departments BLOB, joiningDate FROZEN<TUPLE<TIMESTAMP, TEXT>>, age INT,contained BLOB,referenced BLOB,  PRIMARY KEY (studId));
DROP TABLE IF EXISTS referenced;
CREATE TABLE IF NOT EXISTS referenced(ref1 TEXT, ref2 BOOLEAN, ref3 FROZEN<TUPLE<TIMESTAMP, TEXT>>,  PRIMARY KEY (ref1));
DROP TABLE IF EXISTS contained;
CREATE TABLE IF NOT EXISTS contained(cont1 TEXT, cont2 INT, PRIMARY KEY (cont1));

[CassandraAsChannel.zip](https://github.com/TIBCOSoftware/be-contribution/files/11460057/CassandraAsChannel.zip)
[CassandraStore_ContainedReference.zip](https://github.com/TIBCOSoftware/be-contribution/files/11460058/CassandraStore_ContainedReference.zip)

**Comment by rakulkar-tibco** [comment]
For tuple type, raised the issue on cdc-apache-cassandra git repo.
https://github.com/datastax/cdc-apache-cassandra/issues/160

For contained/ref concepts - use a constructor to create them. Seems there is issue with xslt. With that you should be able to receive corresponding blob data in a message on pulsar topic. 

It will be the user's responsibility to handle blob data.

**Comment by praagraw-tibco** [comment]
For store catalog function: It was displaying "null" values for contained/referenced concepts since there will be no relationship under catalog function.
For the tables generated via studio schema: I can see blob value in table for the contained/referenced concept.
