### ISSUE TITLE
Cassandra Channel || Count of msg is displaying in data topic for the records inserted before pulsar connector NAR is deployed

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#102]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |       6.3.0          |
| OS Type?     |                 |
| OS Version?           |                 |

I can see the count of messages in the data topic (pulsar-admin topics stats <data-topic>) for the records which are inserted before deploying pulsar connector NAR into pulsar cluster.  Can you confirm if we are expecting like this? 

Steps to reproduce:
Create Keyspace and table with cdc as true
Insert the record
Start the BE- Engine
Now deploy the pulsar connector NAR file into pulsar cluster
Check the "msg counter in" for data topic. It's displaying the count of records previously inserted before deployment.
Check the engine logs, it's displaying the consumed messages as well as soon as pulsar connector NAR is deployed.

**Comment by rakulkar-tibco** [comment]
The CDC agent is deployed on the Cassandra node which is already running or started. The CDC agent is responsible for event production on the Cassandra node. As per documentation, it does not sync data available before starting the CDC agent.

But as our cdc agent is already running we are able to see messages after source connector deployment.

**Comment by praagraw-tibco** [comment]
Closed as per dev comment
