### ISSUE TITLE
Channel support for AWS SQS

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-contribution#11]
Context

Channel to support AWS SQS send & receive operation.
Must support SAML Authentication type using AWS+ADFS.

Alternatives

Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

Has the feature been requested before?

Please provide a link to the issue.

If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by vpatil-tibco** [comment]
This is implemented.
