### ISSUE TITLE
Remove PatternMatcher Catalog functions from git repo

### ISSUE THREAD

**Issue by rakulkar-tibco** [TIBCOSoftware/be-contribution#128]
Remove PatternMatcher Catalog functions from git repo, as we have decided to add this back as OOB feature in BE.

**Comment by spingale-tibco** [comment]
Agree Fixed, Pattern Matcher example reverted back to OOB feature in BE.
[PatternMatcherExecution.zip](https://github.com/TIBCOSoftware/be-contribution/files/12287374/PatternMatcherExecution.zip)
