### ISSUE TITLE
Need to document the limitation for Redis database.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-contribution#22]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |    6.1.0-HF-1             |
| OS Type?     |      Any           |
| OS Version?           |     Any         |

### What is the expected behavior?
The user should be able to choose/switch to different database in Redis other than default database 0.
 
### What is the actual behavior?
Currently user cannot use any other database except default database 0 in Redis.

This is a known issue with Redis database. For more info., please refer --> https://github.com/RediSearch/RediSearch/issues/367

**Comment by vpatil-tibco** [comment]
Frankly this is more of the Redis issue than a common behavior in BE. If at all this was a very common usecase/behavior folks would tend to use in BE across we can think about documenting it. But for now. It fine for folk to visit Redis docs for details/limitations. if any.
