### ISSUE TITLE
Catalog functions support for Cassandra

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-contribution#78]
**Context**

Adding catalog function support for cassandra. This should be inline to other implementations i.e. AS4 and Ignite.

**Alternatives**

Yes, a manual implementation will have to be provided by field/customers.

**Has the feature been requested before?**

Yes, informally asked via few field folks as well as customers. SR - https://supportapps.na.tibco.com/query?q=02139348&s=ka&p=kwbe

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by rakulkar-tibco** [comment]
@vilasshelar QA can start testing this feature. 
Also updated existing ActiveSpaces example to demonstrate Cassandra catalog functions.

**Comment by vpatil-tibco** [comment]
Implemented.
