### ISSUE TITLE
AWS SQS Channel to support SAML Authentication with ADFS IdP 

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-contribution#8]
**Context**

What are you trying to do and how would you want to do it differently?  SAML Authentication with ADFS Identity Provider

Is it something you currently you cannot do? Yes 

Is this related to an issue/problem? No

**Alternatives**

Can you achieve the same result doing it in an alternative way? No
Is the alternative considerable? No

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by vpatil-tibco** [comment]
This is implemented.
