### ISSUE TITLE
Cassandra Store Catalog Function || Require to add "cassandra" under description

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#83]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             | 6.3.0                |
| OS Type?     |  NA               |
| OS Version?           |   NA              |

### What is the expected behavior?
1. For Catalog common functions, in Description need to add Cassandra related details, same as we have added for Activespaces and Ignite Cache
2. We have added Cassandra related Catalog function in Custom Functions. While making changes in code, we are able to see same function category 2 times.
Which might confuse which function catalog need to use. Is there any way to update this?

Please find below screenshot for reference.
<img width="669" alt="Function_Description" src="https://user-images.githubusercontent.com/127474249/229704191-0ac8ecac-a62d-4713-a10d-9d3f4c355a9e.PNG">
<img width="718" alt="FunctionCategory" src="https://user-images.githubusercontent.com/127474249/229704203-446e0b58-7ec0-4659-a895-1239476ff82a.PNG">

### What is the actual behavior?
1. For Catalog common functions, Description is related to Activespaces and Ignite Cache
2. For Custom Functions, function category is displayed 2 times.

**Comment by rakulkar-tibco** [comment]
1. As this is not part of installation - we can not add description in catalog common functions for Cassandra.
2. This is expected behavior. As one is OOB and one is for custom additions.
