### ISSUE TITLE
Cassandra Store Catalog Function || Need to add a step in TIBCO BusinessEvents® Contribution readme for Cassandra Store

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#85]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |    6.3.0             |
| OS Type?     |                 | NA
| OS Version?           |   NA              |

### What is the expected behavior?
In TIBCO BusinessEvents® Contribution readme, below step need to add:

For Cassandra Store Catalog Function, while performing **mvn clean install** step, add attribute **Dmaven.test.skip=true** or Cassandra Server should be running on your local machine
ex: mvn clean install -Dmaven.test.skip=true

### What is the actual behavior?
Step **Dmaven.test.skip=true** attribute is required while creating cassandra store catalog function jar which is not mentioned in TIBCO BusinessEvents® Contribution readme

**Comment by rakulkar-tibco** [comment]
[Used Cassandra test container, so that there is no need to explicitly set up Cassandra for unit test cases.
Also no need using property maven.test.skip=true while doing mvn packaging.

**Comment by vpatil-tibco** [comment]
Implemented
