### ISSUE TITLE
Cassandra Store Catalog Function || Issue with ExecuteUpdate() function

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#88]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |      6.3.0           |
| OS Type?     |                 | NA
| OS Version?           |     NA            |

### What is the expected behavior?
ExecuteUpdate() should work with all type of supported queries like Insert, Update, Delete, Index, CreateTable, AlterTable, DropTable and return correct count. Also same should get reflect in cassandra store.

### What is the actual behavior?
executeUpdate when ran with supported  queries, returns count as -1, and also not getting reflecting in store.

### Please provide log files.
[ExecuteUpdateTest1.log](https://github.com/TIBCOSoftware/be-contribution/files/11199477/ExecuteUpdateTest1.log)
[ActiveSpaces_ExecuteUpdate.zip](https://github.com/TIBCOSoftware/be-contribution/files/11199480/ActiveSpaces_ExecuteUpdate.zip)

**Comment by rakulkar-tibco** [comment]
Fixed, but it will still return -1 as there is no provision in Cassandra to get number of rows affected.

**Comment by spingale-tibco** [comment]
executeUpdate() is working with Insert, Update and Delete statement

While creating and deleting the Table/Index we are getting below exception  
'Caused by: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S'

[ExeuteUpdateFinal34.log](https://github.com/TIBCOSoftware/be-contribution/files/11220831/ExeuteUpdateFinal34.log)

**Comment by rakulkar-tibco** [comment]
executeUpdate() is working with Insert, Update and Delete statement

While creating and deleting the Table/Index we are getting below exception
'Caused by: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S'

But on db side we can see the changes

**Comment by spingale-tibco** [comment]
Existing cluster had multiple keyspaces and tables. We were getting this server side warning `Cluster already contains 397 tables in 124 keyspaces. Having a large number of tables will significantly slow down schema dependent cluster operations.`

Hence, As discussed with Rashmi, tried to execute test with different cluster. table create/deletion and Index create/delete is working with another cluster.

[ExecuteUpdateTable105.log](https://github.com/TIBCOSoftware/be-contribution/files/11261637/ExecuteUpdateTable105.log)
