### ISSUE TITLE
BE-6.3.0||Cassandra Channel || Message is not getting consumed and reflecting back during restarting of engine

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#92]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |       6.3.0          |
| OS Type?     |                 |
| OS Version?           |                 |

There are 2 issues being observed:

MSG Counter variable is incrementing for data topic whenever BE-Engine is restarted
Message is not getting consumed and reflecting back during engine restart.

### What is the actual behavior?

MSG Counter variable is incrementing for data topic whenever BE-Engine is restarted
Message is not getting consumed and reflecting back during engine restart.

### Other notes on how to reproduce the issue?
Steps to reproduce:
Cassandra server should be up and running.
Pulsar should be up and running
Deploy pulsar connector NAR file in the Pulsar cluster with required configuration.
Insert a record into Cassandra database.
Start the BE-Engine. (During this msgIn counter and msgOut Counter variables for data topic will display as '1' and msg will display in engine logs )
Close the BE-Engine and restart. (Msgout counter variable value changed to '2' and msg will display in engine logs)

### Please provide log files.

[BE-31626.zip](https://github.com/TIBCOSoftware/be-contribution/files/11292935/BE-31626.zip)

**Comment by rakulkar-tibco** [comment]
There is an issue with pulsar channel implementation.

**Comment by praagraw-tibco** [comment]
Logged issue in JIRA: https://jira.tibco.com/browse/BE-31651

**Comment by rakulkar-tibco** [comment]
Pulsar guarantees at least once delivery of messages.
User can change initial position using destination property ( set it to Latest) so that the start consuming position will be the last message.
